window.regionContacts = {};

(function regionContacts(exports) {
  exports.regionContactsList = {
    mc: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Лысенко Эдуард Анатольевич',
        position: 'Министр Правительства Москвы, руководитель Департамента информационных технологий города Москвы',
        phone: '+7 (495) 620-20-00<br>(доб. 11133)',
        email: 'PR_Lysenko@mos.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Бородин Андрей Александрович',
        position: 'Заместитель руководителя Департамента информационных технологий города Москвы',
        phone: '+7 (495) 620-20-00<br>(доб. 11534)',
        email: 'BorodinAA@mos.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Иванов Дмитрий Александрович',
        position: 'Директор департамента системы государственных услуг Департамента информационных технологий города Москвы',
        phone: '+7 (495) 620-20-00<br>(доб. 11138)',
        email: 'IvanovDA@mos.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Бутурлин Иван Александрович',
        position: 'Начальник аналитического управления Департамента информационных технологий города Москвы',
        phone: '+7 (495) 620-20-00<br>(доб. 11528)',
        email: 'ButurlinIA@mos.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Онтоев Дмитрий Владимирович',
        position: 'Заместитель начальника аналитического управления Департамента информационных технологий города Москвы',
        phone: '+7 (495) 620-20-00<br>(доб. 77302)',
        email: 'OntoevDV@it.mos.ru',
      },
    ],
    sp: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Кучеренко Анастасия Сергеевна',
        position: 'Начальник отдела по взаимодействию с органами власти и организациями при предоставлении государственных и муниципальных услуг',
        phone: '+7 (812) 576-48-39',
        email: 'kucherenko.a@kis.gov.spb.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Воронина Ксения Геннадьевна',
        position: 'Главный специалист отдела по взаимодействию с органами власти и организациями при предоставлении государственных и муниципальных услуг',
        phone: '+7 (812) 576-48-53',
        email: 'voronina@kis.gov.spb.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Лихолетов Андрей Вольдемарович',
        position: 'Начальник отдела информационно-компьютерной безопасности Управления информационной безопасности и технической защиты информации',
        phone: '+7 (812) 576-78-52',
        email: 'likholetov@kis.gov.spb.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Бушихин Игорь Викторович',
        position: 'Начальник отдела городских телекоммуникаций и развития сетей связи',
        phone: '+7 (812) 576-44-35',
        email: 'bushihin@kis.gov.spb.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Соловьева Екатерина Олеговна',
        position: 'Начальник сектора мониторинга общественного мнения',
        phone: '+7 (812) 576-79-60',
        email: 'solovyeva@kis.gov.spb.ru',
      },
    ],
    sl: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Осипова Александра Александровна',
        position: 'Заместитель начальника Главного управления - начальник управления информатизации',
        phone: '+7 (8692) 41-76-76',
        email: 'a.osipova@sev.gov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Тимофеев Денис Александрович',
        position: 'Заместитель начальника Главного управления',
        phone: '+7 (8692) 40-41-90',
        email: 'denis.timofeev@sev.gov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Чугунов Андрей Анатольевич',
        position: 'Начальник Управления цифрового развития и реализации государственных программ',
        phone: '',
        email: 'andrey.chugunov@sev.gov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Черноусова Татьяна Романовна',
        position: 'Заместитель начальника управления - начальник отдела планирования и цифрового развития Управления цифрового развития и реализации государственных программ',
        phone: '+7 (8692) 41-76-95',
        email: 'tatiana.chernousova@sev.gov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Мирошниченко Юлия Владимировна',
        position: 'Главный специалист-эксперт отдела планирования и цифрового развития Управления цифрового развития и реализации государственных программ',
        phone: '+7 (8692) 54-37-65',
        email: 'yulia.miroshnichenko@sev.gov.ru',
      },
    ],
    al: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Зрюмов Евгений Александрович',
        position: 'Министр',
        phone: '+7 (3852) 53-85-19',
        email: 'eaz@alregn.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Поздерин Евгений Николаевич',
        position: 'Заместитель министра',
        phone: '+7 (3852) 53-82-58',
        email: 'enp@alregn.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Чегров Дмитрий Владимирович',
        position: 'Заместитель министра',
        phone: '+7 (3852) 53-82-63',
        email: 'chegrov@alregn.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Долгова Елена Юрьевна',
        position: 'Начальник отдела реализации федеральных программ и проектов',
        phone: '+7 (3852) 53-82-64',
        email: 'dolgova@alregn.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Павлиди Наталья Георгиевна',
        position: 'Заместитель директора',
        phone: '+7 (3852) 20-10-67',
        email: 'ngp@oepak22.ru',
      },
    ],
    am: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Курдюков Александр Михайлович',
        position: 'Начальник управления информатизации области',
        phone: '+7 (4162) 59-62-55',
        email: 'KurdyukovAM@amurobl.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Земнухов Денис Владимирович',
        position: 'Заместитель начальника управления – начальник отдела развития информационного общества, связи и цифровой экономики',
        phone: '+7 (4162) 59-62-56',
        email: 'ZemnuhovDV@amurobl.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Скок Анна Васильевна',
        position: 'Консультант отдела развития информационного общества, связи и цифровой экономики управления информатизации области',
        phone: '+7 (4162) 59-62-58',
        email: 'Skok.AV@amurobl.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Добровольская Ирина Викторовна',
        position: 'Начальник отдела организации предоставления услуг в электронном виде управления информатизации области',
        phone: '+7 (4162) 59-62-59',
        email: 'Dobrovolskaya@amurobl.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Щербаков Сергей Викторович',
        position: 'Руководитель ГБУ «Центр информационных технологий» области',
        phone: '+7 (4162) 59-62-96',
        email: 'Sherbakovsv@amur-cit.ru',
      },
    ],
    ar: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Родичев Николай Петрович',
        position: 'Министр связи и информационных технологий Архангельской области',
        phone: '+7 (8182) 28-83-09',
        email: 'rodichev@dvinaland.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Шамов Виктор Анатольевич',
        position: 'Заместитель министра связи и информационных технологий Архангельской области',
        phone: '+7 (8182) 28-83-09',
        email: 'vshamov@dvinaland.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Девина Ольга Владимировна',
        position: 'Начальник информационно-аналитического отдела министерства связи  и информационных технологий Архангельской области',
        phone: '+7 (8182) 28-83-89',
        email: 'devinaov@dvinaland.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Мальцев Алексей Вячеславович',
        position: 'Начальник отдела информатизации министерства связи и информационных технологий Архангельской области',
        phone: '+7 (8182) 28-81-12',
        email: 'avmaltsev@dvinaland.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Шелюк Илья Сергеевич',
        position: 'Начальник отдела развития связи  и  телекоммуникаций министерства связи и информационных технологий Архангельской области',
        phone: '+7 (8182) 28-96-24',
        email: 'shelukis@dvinaland.ru',
      },
    ],
    as: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Афанасьев Денис Александрович',
        position: 'И.о. министра промышленности, транспорта и природных ресурсов Астраханской области',
        phone: '+7 (8512) 51-46-97',
        email: 'dafanasyev@astrobl.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Кучина Ольга Владимировна',
        position: 'Начальник отдела технологий и проектов электронного правительства департамента административной реформы и электронного правительства министерств экономического развития Астраханской области',
        phone: '+7 (8512) 51-34-19',
        email: 'okuchina@astrobl.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Брыкин Сергей Павлович',
        position: 'Директор государственного бюджетного учреждения Астраханской области «Инфраструктурный центр электронного правительства»',
        phone: '+7 (8512) 51-87-06',
        email: 'sbrykin@astrobl.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Калиновский Владимир Александрович',
        position: 'Заместитель начальника управления связи, массовых коммуникаций и информационно-технического взаимодействия министерства промышленности, транспорта и природных ресурсов Астраханской области',
        phone: '+7 (8512) 44-67-26',
        email: 'vkalinovskiy@astrobl.ru',
      },
    ],
    bl: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Кравченко Олег Александрович',
        position: 'Заместитель начальника департамента - начальник управления развития инфраструктуры цифровой экономики департамента цифрового развития Белгородской области',
        phone: '+7 (4722) 33-68-13',
        email: 'kravchenko_oa@belregion.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Баранов Дмитрий Юрьевич',
        position: 'Начальник управления развития информационного общества департамента цифрового развития Белгородской области',
        phone: '+7 (4722) 32-25-24',
        email: 'baranov@belregion.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Уварова Ксения Александровна',
        position: 'Заместитель начальника управления - начальник отдела реализации отраслевых проектов управления развития инфраструктуры цифровой экономики департамента цифрового развития Белгородской области',
        phone: '+7 (4722) 32-04-06',
        email: 'uvarova_ka@belregion.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Канищев Александр Анатольевич',
        position: 'Заместитель начальника управления - начальник отдела информационной безопасности управления развития инфраструктуры цифровой экономики департамента цифрового развития Белгородской области',
        phone: '+7 (4722) 33-67-37',
        email: 'kanischev_aa@belregion.ru',
      },
    ],
    bn: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Ерохин Михаил Андреевич',
        position: 'Директор департамента экономического развития Брянской области',
        phone: '+7 (4832) 74-20-25',
        email: 'info@econom32.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Маликов Алексей Николаевич',
        position: 'Начальник управления информационных технологий',
        phone: '+7 (4832) 66-19-54',
        email: 'a.malikov@econom32.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Кочуков Виталий Анатольевич',
        position: 'Начальник отдела информационных технологий, связи и защиты информации управления информационных технологий департамента',
        phone: '+7 (4832) 66-51-75',
        email: 'it@econom32.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Белозор Екатерина Павловна',
        position: 'Начальник отдела государственных и муниципальных услуг управления информационных технологий департамента',
        phone: '+7 (4832) 66-14-95',
        email: 'admref.bryansk@yandex.ru',
      },
    ],
  };
}(window.regionContacts));
