window.regionData = {};

(function regionData(exports) {
  exports.regionDataList = [
    {
      code: 'mc',
      name: 'г. Москва',
      picture: 'img/coat/coat_mc.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.mc,
    },
    {
      code: 'sp',
      name: 'г. Санкт-Петербург',
      picture: 'img/coat/coat_sp.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.sp,
    },
    {
      code: 'sl',
      name: 'г. Севастополь',
      picture: 'img/coat/coat_sl.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.sl,
    },
    {
      code: 'al',
      name: 'Алтайский край',
      picture: 'img/coat/coat_al.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.al,
    },
    {
      code: 'am',
      name: 'Амурская область',
      picture: 'img/coat/coat_am.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.am,
    },
    {
      code: 'ar',
      name: 'Архангельская область',
      picture: 'img/coat/coat_ar.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ar,
    },
    {
      code: 'as',
      name: 'Астраханская область',
      picture: 'img/coat/coat_as.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.as,
    },
    {
      code: 'bl',
      name: 'Белгородская область',
      picture: 'img/coat/coat_bl.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.bl,
    },
    {
      code: 'bn',
      name: 'Брянская область',
      picture: 'img/coat/coat_bn.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.bn,
    },
    {
      code: 'vm',
      name: 'Владимирская область',
      picture: 'img/coat/coat_vm.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.vm,
    },
    {
      code: 'vl',
      name: 'Волгоградская область',
      picture: 'img/coat/coat_vl.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.vl,
    },
    {
      code: 'vo',
      name: 'Вологодская область',
      picture: 'img/coat/coat_vo.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.vo,
    },
    {
      code: 'vn',
      name: 'Воронежская область',
      picture: 'img/coat/coat_vn.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.vn,
    },
    {
      code: 'eu',
      name: 'Еврейская автономная область',
      picture: 'img/coat/coat_eu.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.eu,
    },
    {
      code: 'zb',
      name: 'Забайкальский край',
      picture: 'img/coat/coat_zb.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.zb,
    },
    {
      code: 'iv',
      name: 'Ивановская область',
      picture: 'img/coat/coat_iv.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.iv,
    },
    {
      code: 'ir',
      name: 'Иркутская область',
      picture: 'img/coat/coat_ir.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ir,
    },
    {
      code: 'kb',
      name: 'Кабардино-Балкарская Республика',
      picture: 'img/coat/coat_kb.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.kb,
    },
    {
      code: 'kn',
      name: 'Калининградская область',
      picture: 'img/coat/coat_kn.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.kn,
    },
    {
      code: 'kj',
      name: 'Калужская область',
      picture: 'img/coat/coat_kj.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.kj,
    },
    {
      code: 'ka',
      name: 'Камчатский край',
      picture: 'img/coat/coat_ka.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ka,
    },
    {
      code: 'kc',
      name: 'Карачаево-Черкесская Республика',
      picture: 'img/coat/coat_kc.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.kc,
    },
    {
      code: 'km',
      name: 'Кемеровская область',
      picture: 'img/coat/coat_km.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.km,
    },
    {
      code: 'ki',
      name: 'Кировская область',
      picture: 'img/coat/coat_ki.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ki,
    },
    {
      code: 'kt',
      name: 'Костромская область',
      picture: 'img/coat/coat_kt.svg',
      link: '#',
      place: '-',
      index: '-/-',
    },
    {
      code: 'ks',
      name: 'Краснодарский край',
      picture: 'img/coat/coat_ks.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ks,
    },
    {
      code: 'kr',
      name: 'Красноярский край',
      picture: 'img/coat/coat_kr.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.kr,
    },
    {
      code: 'ku',
      name: 'Курганская область',
      picture: 'img/coat/coat_ku.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ku,
    },
    {
      code: 'ky',
      name: 'Курская область',
      picture: 'img/coat/coat_ky.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ky,
    },
    {
      code: 'le',
      name: 'Ленинградская область',
      picture: 'img/coat/coat_le.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.le,
    },
    {
      code: 'lp',
      name: 'Липецкая область',
      picture: 'img/coat/coat_lp.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.lp,
    },
    {
      code: 'ma',
      name: 'Магаданская область',
      picture: 'img/coat/coat_ma.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ma,
    },
    {
      code: 'mo',
      name: 'Московская область',
      picture: 'img/coat/coat_mo.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.mo,
    },
    {
      code: 'mu',
      name: 'Мурманская область',
      picture: 'img/coat/coat_mu.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.mu,
    },
    {
      code: 'ne',
      name: 'Ненецкий автономный округ',
      picture: 'img/coat/coat_ne.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ne,
    },
    {
      code: 'nn',
      name: 'Нижегородская область',
      picture: 'img/coat/coat_nn.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.nn,
    },
    {
      code: 'no',
      name: 'Новгородская область',
      picture: 'img/coat/coat_no.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.no,
    },
    {
      code: 'nv',
      name: 'Новосибирская область',
      picture: 'img/coat/coat_nv.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.nv,
    },
    {
      code: 'om',
      name: 'Омская область',
      picture: 'img/coat/coat_om.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.om,
    },
    {
      code: 'ob',
      name: 'Оренбургская область',
      picture: 'img/coat/coat_ob.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ob,
    },
    {
      code: 'or',
      name: 'Орловская область',
      picture: 'img/coat/coat_or.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.or,
    },
    {
      code: 'pz',
      name: 'Пензенская область',
      picture: 'img/coat/coat_pz.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.pz,
    },
    {
      code: 'pe',
      name: 'Пермский край',
      picture: 'img/coat/coat_pe.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.pe,
    },
    {
      code: 'pr',
      name: 'Приморский край',
      picture: 'img/coat/coat_pr.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.pr,
    },
    {
      code: 'ps',
      name: 'Псковская область',
      picture: 'img/coat/coat_ps.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ps,
    },
    {
      code: 'ad',
      name: 'Республика Адыгея',
      picture: 'img/coat/coat_ad.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ad,
    },
    {
      code: 'lt',
      name: 'Республика Алтай',
      picture: 'img/coat/coat_lt.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.lt,
    },
    {
      code: 'bs',
      name: 'Республика Башкортостан',
      picture: 'img/coat/coat_bs.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.bs,
    },
    {
      code: 'br',
      name: 'Республика Бурятия',
      picture: 'img/coat/coat_br.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.br,
    },
    {
      code: 'da',
      name: 'Республика Дагестан',
      picture: 'img/coat/coat_da.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.da,
    },
    {
      code: 'in',
      name: 'Республика Ингушетия',
      picture: 'img/coat/coat_in.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.in,
    },
    {
      code: 'kk',
      name: 'Республика Калмыкия',
      picture: 'img/coat/coat_kk.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.kk,
    },
    {
      code: 'kl',
      name: 'Республика Карелия',
      picture: 'img/coat/coat_kl.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.kl,
    },
    {
      code: 'ko',
      name: 'Республика Коми',
      picture: 'img/coat/coat_ko.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ko,
    },
    {
      code: 'cr',
      name: 'Республика Крым',
      picture: 'img/coat/coat_cr.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.cr,
    },
    {
      code: 'ml',
      name: 'Республика Марий Эл',
      picture: 'img/coat/coat_ml.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ml,
    },
    {
      code: 'mr',
      name: 'Республика Мордовия',
      picture: 'img/coat/coat_mr.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.mr,
    },
    {
      code: 'sa',
      name: 'Республика Саха (Якутия)',
      picture: 'img/coat/coat_sa.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.sa,
    },
    {
      code: 'so',
      name: 'Республика Северная Осетия-Алания',
      picture: 'img/coat/coat_so.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.so,
    },
    {
      code: 'ta',
      name: 'Республика Татарстан',
      picture: 'img/coat/coat_ta.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ta,
    },
    {
      code: 'tv',
      name: 'Республика Тыва',
      picture: 'img/coat/coat_tv.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.tv,
    },
    {
      code: 'hk',
      name: 'Республика Хакасия',
      picture: 'img/coat/coat_hk.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.hk,
    },
    {
      code: 'ro',
      name: 'Ростовская область',
      picture: 'img/coat/coat_ro.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ro,
    },
    {
      code: 'rz',
      name: 'Рязанская область',
      picture: 'img/coat/coat_rz.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.rz,
    },
    {
      code: 'ss',
      name: 'Самарская область',
      picture: 'img/coat/coat_ss.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ss,
    },
    {
      code: 'sr',
      name: 'Саратовская область',
      picture: 'img/coat/coat_sr.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.sr,
    },
    {
      code: 'sh',
      name: 'Сахалинская область',
      picture: 'img/coat/coat_sh.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.sh,
    },
    {
      code: 'sv',
      name: 'Свердловская область',
      picture: 'img/coat/coat_sv.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.sv,
    },
    {
      code: 'sm',
      name: 'Смоленская область',
      picture: 'img/coat/coat_sm.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.sm,
    },
    {
      code: 'st',
      name: 'Ставропольский край',
      picture: 'img/coat/coat_st.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.st,
    },
    {
      code: 'tb',
      name: 'Тамбовская область',
      picture: 'img/coat/coat_tb.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.tb,
    },
    {
      code: 'tr',
      name: 'Тверская область',
      picture: 'img/coat/coat_tr.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.tr,
    },
    {
      code: 'tm',
      name: 'Томская область',
      picture: 'img/coat/coat_tm.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.tm,
    },
    {
      code: 'tl',
      name: 'Тульская область',
      picture: 'img/coat/coat_tl.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.tl,
    },
    {
      code: 'tu',
      name: 'Тюменская область',
      picture: 'img/coat/coat_tu.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.tu,
    },
    {
      code: 'ud',
      name: 'Удмуртская Республика',
      picture: 'img/coat/coat_ud.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ud,
    },
    {
      code: 'ul',
      name: 'Ульяновская область',
      picture: 'img/coat/coat_ul.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ul,
    },
    {
      code: 'ha',
      name: 'Хабаровский край',
      picture: 'img/coat/coat_ha.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ha,
    },
    {
      code: 'ht',
      name: 'Ханты-Мансийский автономный округ-Югра',
      picture: 'img/coat/coat_ht.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ht,
    },
    {
      code: 'ce',
      name: 'Челябинская область',
      picture: 'img/coat/coat_ce.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ce,
    },
    {
      code: 'cc',
      name: 'Чеченская Республика',
      picture: 'img/coat/coat_cc.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.cc,
    },
    {
      code: 'cu',
      name: 'Чувашская Республика',
      picture: 'img/coat/coat_cu.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.cu,
    },
    {
      code: 'ch',
      name: 'Чукотский автономный округ',
      picture: 'img/coat/coat_ch.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ch,
    },
    {
      code: 'ya',
      name: 'Ямало-Ненецкий автономный округ',
      picture: 'img/coat/coat_ya.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.ya,
    },
    {
      code: 'yr',
      name: 'Ярославская область',
      picture: 'img/coat/coat_yr.svg',
      link: '#',
      place: '-',
      index: '-/-',
      contacts: window.regionContacts.regionContactsList.yr,
    },
  ];
}(window.regionData));
