window.regionContacts = {};

(function regionContacts(exports) {
  exports.regionContactsList = {
    mc: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Лысенко Эдуард Анатольевич',
        position: 'Министр Правительства Москвы, руководитель Департамента информационных технологий города Москвы',
        phone: '+7 (495) 620-20-00<br>(доб. 11133)',
        email: 'PR_Lysenko@mos.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Бородин Андрей Александрович',
        position: 'Заместитель руководителя Департамента информационных технологий города Москвы',
        phone: '+7 (495) 620-20-00<br>(доб. 11534)',
        email: 'BorodinAA@mos.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Иванов Дмитрий Александрович',
        position: 'Директор департамента системы государственных услуг Департамента информационных технологий города Москвы',
        phone: '+7 (495) 620-20-00<br>(доб. 11138)',
        email: 'IvanovDA@mos.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Бутурлин Иван Александрович',
        position: 'Начальник аналитического управления Департамента информационных технологий города Москвы',
        phone: '+7 (495) 620-20-00<br>(доб. 11528)',
        email: 'ButurlinIA@mos.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Онтоев Дмитрий Владимирович',
        position: 'Заместитель начальника аналитического управления Департамента информационных технологий города Москвы',
        phone: '+7 (495) 620-20-00<br>(доб. 77302)',
        email: 'OntoevDV@it.mos.ru',
      },
    ],
    sp: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Кучеренко Анастасия Сергеевна',
        position: 'Начальник отдела по взаимодействию с органами власти и организациями при предоставлении государственных и муниципальных услуг',
        phone: '+7 (812) 576-48-39',
        email: 'kucherenko.a@kis.gov.spb.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Воронина Ксения Геннадьевна',
        position: 'Главный специалист отдела по взаимодействию с органами власти и организациями при предоставлении государственных и муниципальных услуг',
        phone: '+7 (812) 576-48-53',
        email: 'voronina@kis.gov.spb.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Лихолетов Андрей Вольдемарович',
        position: 'Начальник отдела информационно-компьютерной безопасности Управления информационной безопасности и технической защиты информации',
        phone: '+7 (812) 576-78-52',
        email: 'likholetov@kis.gov.spb.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Бушихин Игорь Викторович',
        position: 'Начальник отдела городских телекоммуникаций и развития сетей связи',
        phone: '+7 (812) 576-44-35',
        email: 'bushihin@kis.gov.spb.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Соловьева Екатерина Олеговна',
        position: 'Начальник сектора мониторинга общественного мнения',
        phone: '+7 (812) 576-79-60',
        email: 'solovyeva@kis.gov.spb.ru',
      },
    ],
    sl: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Осипова Александра Александровна',
        position: 'Заместитель начальника Главного управления - начальник управления информатизации',
        phone: '+7 (8692) 41-76-76',
        email: 'a.osipova@sev.gov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Тимофеев Денис Александрович',
        position: 'Заместитель начальника Главного управления',
        phone: '+7 (8692) 40-41-90',
        email: 'denis.timofeev@sev.gov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Чугунов Андрей Анатольевич',
        position: 'Начальник Управления цифрового развития и реализации государственных программ',
        phone: '',
        email: 'andrey.chugunov@sev.gov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Черноусова Татьяна Романовна',
        position: 'Заместитель начальника управления - начальник отдела планирования и цифрового развития Управления цифрового развития и реализации государственных программ',
        phone: '+7 (8692) 41-76-95',
        email: 'tatiana.chernousova@sev.gov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Мирошниченко Юлия Владимировна',
        position: 'Главный специалист-эксперт отдела планирования и цифрового развития Управления цифрового развития и реализации государственных программ',
        phone: '+7 (8692) 54-37-65',
        email: 'yulia.miroshnichenko@sev.gov.ru',
      },
    ],
    al: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Зрюмов Евгений Александрович',
        position: 'Министр',
        phone: '+7 (3852) 53-85-19',
        email: 'eaz@alregn.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Поздерин Евгений Николаевич',
        position: 'Заместитель министра',
        phone: '+7 (3852) 53-82-58',
        email: 'enp@alregn.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Чегров Дмитрий Владимирович',
        position: 'Заместитель министра',
        phone: '+7 (3852) 53-82-63',
        email: 'chegrov@alregn.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Долгова Елена Юрьевна',
        position: 'Начальник отдела реализации федеральных программ и проектов',
        phone: '+7 (3852) 53-82-64',
        email: 'dolgova@alregn.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Павлиди Наталья Георгиевна',
        position: 'Заместитель директора',
        phone: '+7 (3852) 20-10-67',
        email: 'ngp@oepak22.ru',
      },
    ],
    am: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Курдюков Александр Михайлович',
        position: 'Начальник управления информатизации области',
        phone: '+7 (4162) 59-62-55',
        email: 'KurdyukovAM@amurobl.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Земнухов Денис Владимирович',
        position: 'Заместитель начальника управления – начальник отдела развития информационного общества, связи и цифровой экономики',
        phone: '+7 (4162) 59-62-56',
        email: 'ZemnuhovDV@amurobl.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Скок Анна Васильевна',
        position: 'Консультант отдела развития информационного общества, связи и цифровой экономики управления информатизации области',
        phone: '+7 (4162) 59-62-58',
        email: 'Skok.AV@amurobl.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Добровольская Ирина Викторовна',
        position: 'Начальник отдела организации предоставления услуг в электронном виде управления информатизации области',
        phone: '+7 (4162) 59-62-59',
        email: 'Dobrovolskaya@amurobl.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Щербаков Сергей Викторович',
        position: 'Руководитель ГБУ «Центр информационных технологий» области',
        phone: '+7 (4162) 59-62-96',
        email: 'Sherbakovsv@amur-cit.ru',
      },
    ],
    ar: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Родичев Николай Петрович',
        position: 'Министр связи и информационных технологий Архангельской области',
        phone: '+7 (8182) 28-83-09',
        email: 'rodichev@dvinaland.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Шамов Виктор Анатольевич',
        position: 'Заместитель министра связи и информационных технологий Архангельской области',
        phone: '+7 (8182) 28-83-09',
        email: 'vshamov@dvinaland.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Девина Ольга Владимировна',
        position: 'Начальник информационно-аналитического отдела министерства связи  и информационных технологий Архангельской области',
        phone: '+7 (8182) 28-83-89',
        email: 'devinaov@dvinaland.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Мальцев Алексей Вячеславович',
        position: 'Начальник отдела информатизации министерства связи и информационных технологий Архангельской области',
        phone: '+7 (8182) 28-81-12',
        email: 'avmaltsev@dvinaland.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Шелюк Илья Сергеевич',
        position: 'Начальник отдела развития связи  и  телекоммуникаций министерства связи и информационных технологий Архангельской области',
        phone: '+7 (8182) 28-96-24',
        email: 'shelukis@dvinaland.ru',
      },
    ],
    as: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Афанасьев Денис Александрович',
        position: 'И.о. министра промышленности, транспорта и природных ресурсов Астраханской области',
        phone: '+7 (8512) 51-46-97',
        email: 'dafanasyev@astrobl.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Кучина Ольга Владимировна',
        position: 'Начальник отдела технологий и проектов электронного правительства департамента административной реформы и электронного правительства министерств экономического развития Астраханской области',
        phone: '+7 (8512) 51-34-19',
        email: 'okuchina@astrobl.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Брыкин Сергей Павлович',
        position: 'Директор государственного бюджетного учреждения Астраханской области «Инфраструктурный центр электронного правительства»',
        phone: '+7 (8512) 51-87-06',
        email: 'sbrykin@astrobl.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Калиновский Владимир Александрович',
        position: 'Заместитель начальника управления связи, массовых коммуникаций и информационно-технического взаимодействия министерства промышленности, транспорта и природных ресурсов Астраханской области',
        phone: '+7 (8512) 44-67-26',
        email: 'vkalinovskiy@astrobl.ru',
      },
    ],
    bl: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Кравченко Олег Александрович',
        position: 'Заместитель начальника департамента - начальник управления развития инфраструктуры цифровой экономики департамента цифрового развития Белгородской области',
        phone: '+7 (4722) 33-68-13',
        email: 'kravchenko_oa@belregion.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Баранов Дмитрий Юрьевич',
        position: 'Начальник управления развития информационного общества департамента цифрового развития Белгородской области',
        phone: '+7 (4722) 32-25-24',
        email: 'baranov@belregion.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Уварова Ксения Александровна',
        position: 'Заместитель начальника управления - начальник отдела реализации отраслевых проектов управления развития инфраструктуры цифровой экономики департамента цифрового развития Белгородской области',
        phone: '+7 (4722) 32-04-06',
        email: 'uvarova_ka@belregion.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Канищев Александр Анатольевич',
        position: 'Заместитель начальника управления - начальник отдела информационной безопасности управления развития инфраструктуры цифровой экономики департамента цифрового развития Белгородской области',
        phone: '+7 (4722) 33-67-37',
        email: 'kanischev_aa@belregion.ru',
      },
    ],
    bn: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Ерохин Михаил Андреевич',
        position: 'Директор департамента экономического развития Брянской области',
        phone: '+7 (4832) 74-20-25',
        email: 'info@econom32.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Маликов Алексей Николаевич',
        position: 'Начальник управления информационных технологий',
        phone: '+7 (4832) 66-19-54',
        email: 'a.malikov@econom32.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Кочуков Виталий Анатольевич',
        position: 'Начальник отдела информационных технологий, связи и защиты информации управления информационных технологий департамента',
        phone: '+7 (4832) 66-51-75',
        email: 'it@econom32.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Белозор Екатерина Павловна',
        position: 'Начальник отдела государственных и муниципальных услуг управления информационных технологий департамента',
        phone: '+7 (4832) 66-14-95',
        email: 'admref.bryansk@yandex.ru',
      },
    ],
    vm: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Клименко Михаил Евгеньевич',
        position: 'Председатель комитета информатизации, связи и телекоммуникаций администрации Владимирской области',
        phone: '+7 (4922) 32-55-15',
        email: 'kist@avo.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Емшанова Елена Александровна',
        position: 'Заместитель председателя, начальник отдела цифрового развития и перспективных программ комитета информатизации, связи и телекоммуникаций администрации Владимирской области',
        phone: '+7 (4922) 33-11-42',
        email: 'emshanova@avo.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Шуба Павел Михайлович',
        position: 'Заместитель председателя, начальник отдела информационных ресурсов и информационных услуг комитета информатизации, связи и телекоммуникаций администрации Владимирской области',
        phone: '+7 (4922) 52-88-56',
        email: 'shuba@avo.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Уваров  Евгений Владимирович',
        position: 'Начальник отдела аппаратного обеспечения и сетевого администрирования комитета информатизации, связи и телекоммуникаций администрации Владимирской области',
        phone: '+7 (4922) 33-12-04',
        email: 'uvarov-ev@avo.ru',
      },
    ],
    vl: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Торбин Сергей Пантелеевич',
        position: 'Председатель комитета',
        phone: '+7 (8442) 35-22-00, +7 (8442) 35-22-01',
        email: 'S_Torbin@volganet.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Кидалов Алексей Николаевич',
        position: 'Заместитель председателя комитета - начальник отдела развития информационного общества и межведомственных информационных систем',
        phone: '+7 (8442) 35-22-03',
        email: 'A_Kidalov@volganet.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Максимов Максим Сергеевич',
        position: 'Заместитель председателя комитета',
        phone: '+7 (8442) 35-22-02',
        email: 'M_Maksimov@volganet.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Юдина Галина Александровна',
        position: 'Начальник отдела проектного управления и координации региональной информатизации',
        phone: '+7 (8442) 35-22-81',
        email: 'G_Yudina@volganet.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Пименов Александр Юрьевич',
        position: 'Заведующий сектором внедрения и развития отраслевых информационных систем и технологий',
        phone: '+7 (8442) 35-22-43',
        email: 'A_Pimenov@volganet.ru',
      },
    ],
    vo: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Клишина Валерия Юрьевна',
        position: 'Референт',
        phone: '+7 (8172) 23-02-08<br>(доб. 2814)',
        email: 'KlishinaVY@it.gov35.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Бобыкина Надежда Михайловна',
        position: 'Ведущий консультант',
        phone: '+7 (8172) 23-02-08<br>(доб. 2819)',
        email: 'BobykinaNM@it.gov35.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Поликарпова Наталья Сергеевна',
        position: 'Главный советник',
        phone: '+7 (8172) 23-02-08<br>(доб. 2815)',
        email: 'PolikarpovaNS@it.gov35.ru',
      },
    ],
    vn: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Верховцев Артем Юрьевич',
        position: 'Заместитель председателя правительства Воронежской области',
        phone: '+7 (473) 212-75-57',
        email: 'priemnaya-va@govvrn.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Проскурин Дмитрий Константинович',
        position: 'Руководитель департамента цифрового  развития  Воронежской  области',
        phone: '+7 (473) 212-65-05',
        email: 'pdk@govvrn.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Соколов Алексей Серафимович',
        position: 'Заместитель руководителя - начальник отдела цифрового государственного управления департамента цифрового развития Воронежской области',
        phone: '+7 (473) 212-65-07',
        email: 'asokolov@govvrn.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Просвирин Денис Борисович',
        position: 'Заместитель руководителя - начальник отдела развития информационно-телекоммуникационной инфраструктуры департамента цифрового развития Воронежской области',
        phone: '+7 (473) 212-65-11',
        email: 'dprosvirin@govvrn.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Апалихин Сергей Владимирович',
        position: 'Начальник отдела развития систем электронного взаимодействия департамента цифрового развития Воронежской области',
        phone: '+7 (473) 212-65-13',
        email: 'sapalichin@govvrn.ru',
      },
    ],
    eu: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Кованева Светлана Витальевна',
        position: 'Председатель комитета',
        phone: '+7 (42622) 4-06-50',
        email: 'Kovaneva@post.eao.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Шевченко Андрей Викторович',
        position: 'Начальник отдела развития технологий электронного правительства комитета',
        phone: '+7 (42622) 4-14-31',
        email: 'ashev@post.eao.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Ходос Олег Сергеевич',
        position: 'Начальник отдела информационного обеспечения и государственного заказа комитета',
        phone: '+7 (42622) 2-18-26',
        email: 'khodos@post.eao.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Бобылев Евгений Александрович',
        position: 'Начальник отдела геоинформационных систем и связи комитета',
        phone: '+7 (42622) 4-01-49',
        email: 'bobylev@post.eao.ru',
      },
    ],
    zb: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Батуева Евгения Владимировна',
        position: 'Министр',
        phone: '+7 (3022) 23-32-41',
        email: 'batueva@minenergo.e-zab.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Ткачук Екатерина Александровна',
        position: 'Начальник отдела цифровизации государственного управления',
        phone: '+7 (3022) 23-32-78',
        email: 'tkachuk@coms.e-zab.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Ларионов Иван Александрович',
        position: 'Начальник отдела защиты информации',
        phone: '+7 (3022) 23-32-21',
        email: 'larionov@coms.e-zab.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Шлидт Дмитрий Владимирович',
        position: 'Заместитель министра по вопросам информатизации, связи и защиты информации',
        phone: '+7 (3022) 23-32-31',
        email: 'sdv@e-zab.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Кожевников Сергей Сергеевич',
        position: 'Директор',
        phone: '+7 (3022) 35-23-79',
        email: 'infocenter@e-zab.ru',
      },
    ],

    iv: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Иващенко Валерий Александрович',
        position: 'Начальник Департамента развития информационного общества Ивановской области',
        phone: '',
        email: 'iva@gov37.ivanovo.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Тарабцева Ольга Владимировна',
        position: 'Начальник отдела координации предоставления государсвтенных услуг управления региональной информатизации Департамента развития информационного общества Ивановской области',
        phone: '+7 (4932) 90-15-69',
        email: 'tovlad@adminet.ivanovo.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Задворнова Татьяна Ивановна',
        position: 'Начальник отдела разработки, внедрения и сопровождения проектов информатизации управления региональной информатизации Департамента развития информационного общества Ивановской области',
        phone: '+7 (4932) 90-13-73',
        email: 'zadvornova@gov37.ivanovo.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Шишаков Михаил Александрович',
        position: 'Начальник отдела информационных технологий управления региональной информатизации Департамента развития информационного общества Ивановской области',
        phone: '+7 (4932) 90-13-79',
        email: 'admin@gov37.ivanovo.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Суровов Сергей Вячеславович',
        position: 'Главный эксперт по безопасности сектора технической защиты информации Департамента развития информационного общества Ивановской области',
        phone: '+7 (4932) 90-13-76',
        email: 'surovov_sv@ivreg.ru',
      },
    ],
    ir: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Васиченко Евгений Анатольевич',
        position: 'Заместитель министра экономического развития Иркутской области',
        phone: '+7 (3952) 28-66-21',
        email: 'e.vasichenko@govirk.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Белоусова Елена  Сергеевна',
        position: 'Заместитель начальника управления – начальник отдела межведомственного взаимодействия и реализации административной реформы в управлении межведомственного взаимодействия и информационных технологий министерства экономического развития Иркутской области',
        phone: '+7 (3952) 24-14-97',
        email: 'e.belousova@govirk.ru',
      },
    ],
    kb: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Ашхотов Ислам Асланович',
        position: 'Заместитель министра - руководитель департамента развития транспортной инфраструктуры',
        phone: '+7 (88662) 77-84-16',
        email: 'islam.ashkhotov@gmail.com',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Амшуков Алим Эдуардович',
        position: 'Начальник управления цифрового развития',
        phone: '+7 (88662) 77-09-77',
        email: 'amshukov_alim@mail.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Ашабоков Жантемир Борисович',
        position: 'Начальник отдела цифрового развития и информационных технологий - управления цифрового равития Кабардино-Балкарской Республики',
        phone: '+7 (88662) 77-85-08',
        email: 'zhantemir@bk.ru',
      },
    ],
    kn: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Игнатенко Алексей Вячеславович',
        position: 'Министр',
        phone: '+7 (4012) 53-83-55',
        email: 'a.ignatenko@gov39.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Андрианов Владимир Алексеевич',
        position: 'Заместитель начальника департамента цифровых технологий и электронного правительства - начальник отдела развития электронного правительства',
        phone: '+7 (4012) 52-57-78',
        email: 'v.andrianov@gov39.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Сохоров Валерий Александрович',
        position: 'Заместитель министра, начальник департамента связи и управления проектами',
        phone: '+7 (4012) 53-01-90',
        email: 'v.sokhorov@gov39.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Иванов Евгений Вячеславович',
        position: 'Заместитель министра, начальник департамента цифровых технологий и электронного правительства',
        phone: '+7 (4012) 53-01-92',
        email: 'e.ivanov@gov39.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Филонов Андрей Валерьевич',
        position: 'Начальник отдела сопровождения и мониторинга государственных программ и региональных проектов',
        phone: '',
        email: 'a.philonov@gov39.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Жеребко Илона Александровна',
        position: 'Консультант отдела сопровождения и мониторинга государственных программ и региональных проектов',
        phone: '',
        email: 'i.zherebko@gov39.ru',
      },
    ],
    kj: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Андриянов Александр Викторович',
        position: 'Заместитель начальника управления информатизации и связи – начальник отдела развития информационных систем',
        phone: '+7 (4842) 77-85-01',
        email: 'a_ndrian@adm.kaluga.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Поляков Алексей Дмитриевич',
        position: 'Заместитель начальника управления информатизации и связи  – начальник отдела цифровой трансформации',
        phone: '+7 (4842) 77-81-53',
        email: 'polyakov@adm.kaluga.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Воробьева Екатерина Витальевна',
        position: 'Ведущий эксперт отдела цифровой трансформации управления информатизации и связи',
        phone: '+7 (4842) 77-81-62',
        email: 'vorobieva_ev@adm.kaluga.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Ефремова Мария Александровна',
        position: 'Ведущий эксперт отдела цифровой трансформации управления информатизации и связи',
        phone: '+7 (4842) 77-81-55',
        email: 'efremowa_ma@adm.kaluga.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Королева Анна Валерьевна',
        position: 'Ведущий эксперт отдела цифровой трансформации управления информатизации и связи',
        phone: '+7 (4842) 77-81-62',
        email: 'koroleva_av@adm.kaluga.ru',
      },
    ],
    ka: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Леонтьева Инга Михайловна',
        position: 'Руководитель Агентства',
        phone: '+7 (4152) 42-06-49',
        email: 'LeontevaIM@kamgov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Хамлов Максим Петрович',
        position: 'Заместитель руководителя - начальник отдела региональной политики в области информатизации',
        phone: '+7 (4152) 42-09-21',
        email: 'KhamlovMP@kamgov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Егоров Антон Витальевич',
        position: 'Заместитель начальника отдела региональной политики в области информатизации',
        phone: '+7 (4152) 42-09-58',
        email: 'egorovav@kamgov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Бондаренко Григорий Владимирович',
        position: 'Советник отдела региональной политики в области информатизации',
        phone: '+7 (4152) 42-09-58',
        email: 'bondarenkogv@kamgov.ru',
      },
    ],
    kc: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Коваленко Руслан Николаевич',
        position: 'Заместитель министра',
        phone: '+7 (8782) 25-00-02',
        email: 'itminprom@mail.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Карасова Заира Иосифовна',
        position: 'Заместитель министра',
        phone: '+7 (8782) 26-69-59',
        email: 'zairak@mail.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Селиванов Владимир Анатольевич',
        position: 'Заместитель министра',
        phone: '+7 (8782) 26-64-80',
        email: 'minzdrav-kchr@mail.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Грушко  Иван Степанович',
        position: 'Консультант информационно-аналитического, статистического отдела',
        phone: '+7 (8782) 26-64-54',
        email: 'inform-mz@mail.ru',
      },
    ],
    km: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Каплина Ксения Юрьевна',
        position: 'И.о. начальника департаментаа',
        phone: '+7 (3842) 36-67-70',
        email: 'kku@ako.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Шарафутдинова Лилия Рафаиловна',
        position: 'Ведущий консультант',
        phone: '+7 (3842) 36-40-61',
        email: 'ShLR@ako.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Утенкова Ольга Михайловна',
        position: 'Заместитель начальника департамента – начальник управления информатизации',
        phone: '+7 (3842) 58-38-57',
        email: 'olga@ako.ru',
      },
    ],
    ki: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Сухих Алексей Васильевич',
        position: 'Заместитель министра информационных технологий и связи Кировской области',
        phone: '+7 (8332) 27-27-27<br>(доб. 2702)',
        email: 'av.sukhikh@ako.kirov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Малофеев Дмитрий Анатольевич',
        position: 'Заместитель министра, начальник отдела отраслевой информатизации',
        phone: '+7 (8332) 27-27-27<br>(доб. 2720)',
        email: 'd.malofeev@ako.kirov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Попов Андрей Владиславович',
        position: 'Начальник отдела информационной безопасности',
        phone: '+7 (8332) 27-27-27<br>(доб. 2730)',
        email: 'popov.av@ako.kirov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Колышницына Ольга Леонидовна',
        position: 'Ведущий консультант отдела отраслевой информатизации',
        phone: '+7 (8332) 27-27-27<br>(доб. 2724)',
        email: 'kolyshnitcyna.o@ako.kirov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Сенникова Анна Николаевна',
        position: 'Консультант отдела государственных услуг',
        phone: '+7 (8332) 27-27-27<br>(доб. 2713)',
        email: 'sennikova.an@ako.kirov.ru',
      },
    ],
    kt: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Фальчиков Валерий Викторович',
        position: 'Начальник отдела по защите информации управления цифрового развития администрации Костромской области',
        phone: '+7 (4942) 31-60-90',
        email: 'falchikov.vv@adm44.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Данильченко Максим Вениаминович',
        position: 'Начальник отдела проектного управления управления цифрового развития администрации Костромской области',
        phone: '+7 (4942) 37-29-10',
        email: 'dmv@adm44.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Орлова Екатерина Павловна',
        position: 'Заместитель начальника отдела проектного управления управления цифрового развития администрации Костромской области',
        phone: '+7 (4942) 39-83-48',
        email: 'orlova.ep@adm44.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Качалова Светлана Витальевна',
        position: 'Начальник отдела правового и методического обеспечения административной реформы управления цифрового развития администрации Костромской области',
        phone: '+7 (4942) 31-38-12',
        email: 'morozova.sv@adm44.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Новиков Янис Александрович',
        position: 'Начальник отдела развития и сопровождения информационных систем управления цифрового развития администрации Костромской области',
        phone: '+7 (4942) 37-34-81',
        email: 'yanovikov@adm44.ru',
      },
    ],
    ks: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Юшков Евгений Валерьевич',
        position: 'Руководитель',
        phone: '+7 (861) 214-22-00',
        email: 'e.yushkov@dis.krasnodar.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Бережной Денис Сергеевич',
        position: 'Первый заместитель руководителя',
        phone: '+7 (861) 214-22-00',
        email: 'd.berezhnoi@dis.krasnodar.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Романец Роман Андреевич',
        position: 'Заместитель руководителя',
        phone: '+7 (861) 214-22-00',
        email: 'r.romanec@dis.krasnodar.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Головченко Анатолий Сергеевич',
        position: 'Начальник управления',
        phone: '+7 (861) 214-22-13',
        email: 'a.golovchenko@dis.krasnodar.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Бугрий Максим Юрьевич',
        position: 'Начальник управления',
        phone: '+7 (861) 214-22-12',
        email: 'm.bugriy@dis.krasnodar.ru',
      },
    ],
    kr: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Гришко Сергей Николаевич',
        position: 'Заместитель министра - начальник отдела телекоммуникационной инфраструктуры и связи',
        phone: '+ 7 (391) 273-05-10',
        email: 'grishko_sn@digital.krskstate.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Шолеров Николай Александрович',
        position: 'Начальник отдела отраслевых информационных проектов',
        phone: '+7 (391) 273-05-15',
        email: 'sholerov_vn@digital.krskstate.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Рукосуев Александр Олегович',
        position: 'Консультант отдела межведомственного электронного взаимодействия',
        phone: '+7 (391) 273-05-03',
        email: 'rukosuev_ao@digital.krskstate.ru',
      },
    ],
    ku: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Половинкин Алексей Анатольевич',
        position: 'Начальник управления цифрового развития',
        phone: '+7 (3522) 42-90-30',
        email: 'polovinkin_aa@kurganobl.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Фахрутдинова  Гульжан Сапабековна',
        position: 'Временно исполняющий обязанности директора департамента',
        phone: '+7 (3522) 42-92-17',
        email: 'fahrutdinova_gs@kurganobl.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Галактионов Вячеслав Владимирович',
        position: 'Заместитель директора департамента',
        phone: '+7 (3522) 42-91-30',
        email: 'vgal@kurganobl.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Вершинин Сергей Викторович',
        position: 'Начальник управления цифрового развития',
        phone: '+7 (3522) 42-90-90',
        email: 'vershinin@kurganobl.ru',
      },
    ],
    ky: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Абросимов Николай Николаевич',
        position: 'Заместитель начальника управления информационной безопасности и связи',
        phone: '+7 (4712) 39-51-33',
        email: 'abrosimov@rkursk.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Булатникова Юлия Дмитриевна',
        position: 'Главный консультант управления развития информационных технологий (офиса цифровой трансформации)',
        phone: '+7 (4712) 39-51-39',
        email: 'bulatnikova@rkursk.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Ельчина Анастасия Сергеевна',
        position: 'Консультант отдела высшего образования и науки',
        phone: '+7 (4712) 70-05-98',
        email: 'vpo_komobr46@mail.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Заичко Людмила Владимировна',
        position: 'Главный консультант управления информационной безопасности и связи',
        phone: '+7 (4712) 39-51-33',
        email: 'ludmila@rkursk.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Ярешко Елена Александровна',
        position: 'Заместитель начальника управления развития информационных технологий (офиса цифровой трансформации)',
        phone: '+7 (4712) 39-51-39',
        email: 'yareshko@rkursk.ru',
      },
    ],
    le: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Золков  Денис  Викторович',
        position: 'Заместитель председателя комитета цифрового развития Ленинградской области',
        phone: '+7 (812) 611-42-00',
        email: 'dv_zolkov@lenreg.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Хомичев Евгений Александрович',
        position: 'Заместитель начальника ГКУ ЛО «РМЦ»',
        phone: '+7 (812) 611-42-00',
        email: 'ea_khomichev@lenreg.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Кокурин  Александр Александрович',
        position: 'Начальник отдела информационной безопасности комитета цифрового развития Ленинградской области',
        phone: '+7 (812) 611-42-09',
        email: 'aa_kokurin@lenreg.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Козырева Оксана Александровна',
        position: 'Начальник отдела организационно-правового обеспечения и делопроиводства комитета цифрового развития Ленинградской области',
        phone: '+7 (812) 611-42-14',
        email: 'oa_kozyreva@lenreg.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Урусова  Наиля Фяридьевна',
        position: 'Главный специалист отдела стратегических проектов комитета цифрового развития Ленинградской области',
        phone: '+7 (812) 611-42-06',
        email: 'nf_urusova@lenreg.ru',
      },
    ],
    lp: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Якутин Анатолий Владимирович',
        position: 'Заместитель главы администрации Липецкой области',
        phone: '+7 (4742) 27-15-63',
        email: 'avyakutin@admlr.lipetsk.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Корниенко Станислав Альбертович',
        position: 'Начальник управления информатизации администрации Липецкой области',
        phone: '+7 (4742) 22-84-05',
        email: 'kornienko@admlr.lipetsk.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Воронина Ирина Анатольевна',
        position: 'Заместитель начальника управления – начальник отдела управления информатизации администрации Липецкой области',
        phone: '+7 (4742) 22-87-10',
        email: 'voroninaIA@admlr.lipetsk.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Зарникова Надежда Борисовна',
        position: 'Начальник отдела управления информатизации администрации Липецкой области',
        phone: '+7 (4742) 22-86-13',
        email: 'zarnikovaNB@admlr.lipetsk.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Анисимова Марина Викторовна',
        position: 'Заместитель начальника отдела управления информатизации администрации Липецкой области',
        phone: '+7 (4742) 27-48-51',
        email: 'anisimovaMV@admlr.lipetsk.ru',
      },
    ],
    ma: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Мироненко Дмитрий Владимирович',
        position: 'Руководитель департамента информационных технологий и связи Правительства Магаданской области',
        phone: '+7 (4132) 60-78-63',
        email: 'MironenkoDV@49gov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Джафаров Юрий Исламович',
        position: 'Заместитель руководителя департамента - начальник отдела информатизации и систем электронного правительства',
        phone: '+7 (4132) 64-35-77',
        email: 'JafarovYI@49gov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Клюшенков Валентин Андреевич',
        position: 'Заместитель руководителя департамента - начальник отдела телекоммуникаций и связи',
        phone: '+7 (4132) 64-35-07',
        email: 'KlyushenkovVA@49gov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Шарапова Ирина Романовна',
        position: 'Начальник отдела сопровождения информационных систем департамента',
        phone: '+7 (4132) 64-35-61',
        email: 'Sharapova@49gov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Штундюк Василий Юрьевич',
        position: 'Заместитель начальника отдела защиты информации департамента',
        phone: '+7 (4132) 639 131',
        email: 'ShtunduykVU@49gov.ru',
      },
    ],
    mo: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Дроздов Максим Владимирович',
        position: 'Первый заместитель министра государственного управления информационных технологий и связи Московской области',
        phone: '+7 (498) 602-83-23<br>(доб. 48 393)',
        email: 'DrozdovMV@mosreg.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Анопченко Алексей Иванович',
        position: 'Заместитель министра государственного управления информационных технологий и связи Московской области',
        phone: '+7 (498) 602-83-23<br>(доб. 40 281)',
        email: 'AnopchenkoAI@mosreg.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Куртяник Надежда Васильевна',
        position: 'Начальник Управления развития электронного правительства',
        phone: '',
        email: 'KurtyanikNV@mosreg.ru',
      },
    ],
    mu: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Зуева Ирина Александровна',
        position: 'Консультант отдела развития гражданской службы управления государственной службы и кадров',
        phone: '+7 (8152) 48-63-34',
        email: 'iazueva@gov-murman.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Ольнева Вера Александровна',
        position: 'Заместитель начальника отдела развития инноваций и предпринимательства',
        phone: '+7 (8152) 48-65-49',
        email: 'olneva@gov-murman.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Пыхтина Екатерина Валерьевна',
        position: 'Главный специалист отдела целевых программ, ресурсного обеспечения и государственных закупок',
        phone: '+7 (8152) 44-63-86',
        email: 'evpyhtina@gov-murman.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Попов Степан Александрович',
        position: 'Начальник отдела формирования электронного правительства',
        phone: '+7 (8152) 48-64-62',
        email: 'spopov@gov-murman.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Лысенко Денис Александрович',
        position: 'Начальник отдела развития систем коммуникаций',
        phone: '+7 (8152) 48-65-99',
        email: 'ShtunduykVU@49gov.ru',
      },
    ],
    ne: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Окладников Павел Анатольевич',
        position: 'Руководитель Департамента цифрового развития, связи и массовых коммуникаций Ненецкого автономного округа',
        phone: '+7 (81853) 2-19-42',
        email: 'pokladnikov@adm-nao.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Марков Михаил Анатольевич',
        position: 'Председатель комитета цифрового развития и связи Департамента цифрового развития, связи и массовых коммуникаций Ненецкого автономного округа',
        phone: '+7 (81853) 2-19-35',
        email: 'mmarkov@adm-nao.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Тахаутдинов Андрей Масгутович',
        position: 'Начальник сектора инфраструктурного развития и связи комитета цифрового развития и связи Департамента цифрового развития, связи и массовых коммуникаций Ненецкого автономного округа',
        phone: '+7 (81853) 2-19-35',
        email: 'ATakhautdinov@adm-nao.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Рыхлицкая Ирина Владимировна',
        position: 'Начальник сектора цифрового государственного управления комитета цифрового развития и связи Департамента цифрового развития, связи и массовых коммуникаций Ненецкого автономного округа',
        phone: '+7 (81853) 2-19-41',
        email: 'iryhlickaja@adm-nao.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Боярко Антон Вячеславович',
        position: 'Председатель комитета проектной работы-проектного офиса Департамента цифрового развития, связи и массовых коммуникаций Ненецкого автономного округа',
        phone: '+7 (81853) 6-51-79',
        email: 'aboyarko@adm-nao.ru',
      },
    ],
    nn: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Москвин Алексей Анатольевич',
        position: 'Первый заместитель министра – начальник управления ИТ проектов',
        phone: '+7 (831) 216-33-33<br>(доб. 300)',
        email: 'a.moskvin@mininform.kreml.nnov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Воробьев Алексей Валерьевич',
        position: 'Заместитель министра – начальник управления ИТ инфраструктуры, информационной безопасности и связи',
        phone: '+7 (831) 216-33-33<br>(доб. 444)',
        email: 'a.vorobiev@mininform.kreml.nnov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Белова Людмила Юрьевна',
        position: 'Начальник отдела сопровождения ИТ проектов управления ИТ проектов',
        phone: '+7 (831) 216-33-33<br>(доб. 317)',
        email: 'belova@mininform.kreml.nnov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Сурнина Ольга Александровна',
        position: 'Главный специалист отдела сопровождения ИТ проектов управления ИТ проектов',
        phone: '+7 (831) 216-33-33<br>(доб. 301)',
        email: 'soa@mininform.kreml.nnov.ru',
      },
    ],
    no: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Майоров Андрей Владимирович',
        position: 'Заместитель министра',
        phone: '',
        email: 'a.v.mayorov@novreg.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Карпунин Владимир Михайлович',
        position: 'Директор департамента по развитию цифровой экономики и информационно-коммуникационных технологий министерства транспорта, дорожного хозяйства и цифрового развития Новгородской области',
        phone: '+7 (8162) 76-56-36<br>(доб. 1222)',
        email: 'vmk@novreg.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Степанова Эльвира Вячеславовна',
        position: 'Начальник отдела развития цифровой экономики департамента по развитию цифровой экономики и информационно-коммуникационных технологий министерства транспорта, дорожного хозяйства и цифрового развития Новгородской области',
        phone: '+7 (8162) 76-56-36<br>(доб. 1206)',
        email: 'evstep@novreg.ru',
      },
    ],
    nv: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Жучков Павел Анатольевич',
        position: 'Заместитель министра цифрового развития и связи Новосибирской области',
        phone: '+7 (383) 296-97-01',
        email: 'zhpa@nso.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Савельева Ирина Олеговна',
        position: 'Заместитель министра - начальник управления координации мероприятий по цифровой трансформации',
        phone: '+7 (383) 296-97-20',
        email: 'sio@nso.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Цукарь Сергей Сергеевич',
        position: 'Заместитель министра - начальник управления технологий цифрового государства',
        phone: '+7 (383) 296-97-04',
        email: 'csse@nso.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Синицын Кирилл Владимирович',
        position: 'Заместитель руководителя ГБУ НСО «ЦЗИ НСО»',
        phone: '+7 (383) 296-98-90',
        email: 'skv@nso.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Мануйлова Ирина Викторовна',
        position: 'Заместитель министра образования Новосибирской области',
        phone: '+7 (383) 238-73-22',
        email: 'maivi@nso.ru',
      },
    ],
    om: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Сушков Максим Юрьевич',
        position: 'Первый заместитель Министра промышленности, связи,  цифрового и научно-технического развития Омской области',
        phone: '+7 (3812) 77-04-77',
        email: 'msushkov@mps.omskportal.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Барановский Сергей Петрович',
        position: 'Руководитель департамента цифрового  развития, связи и информационной безопасности Министерства промышленности,  связи, цифрового и научно-технического развития Омской области',
        phone: '+7 (3812) 77-04-57',
        email: 'sbaranovskiy@mps.omskportal.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Пушкарев Андрей Иванович',
        position: 'Главный специалист отдела связи департамента  цифрового развития, связи и информационной безопасности Министерства  промышленности, связи, цифрового и научно-технического развития Омской  области',
        phone: '+7 (3812) 77-04-90',
        email: 'apushkarev@mps.omskportal.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Шиповалов Артем Сергеевич',
        position: 'Начальник сводно-аналитического отдела департамента мониторинга социально-экономического развития Министерства экономики Омской области',
        phone: '+7 (3812) 37-40-06',
        email: 'ashipovalov@mineconom.omskportal.ru',
      },
    ],
    ob: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Вечеренко Дмитрий Сергеевич',
        position: 'И.о. заместителя директора – начальник отдела региональной информатизации',
        phone: '+7 (3532) 78-61-15',
        email: 'dsv@mail.orb.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Дробный Юрий Валерьевич',
        position: 'Заместитель начальника отдела региональной информатизации',
        phone: '+7 (3532) 78-68-33',
        email: 'yvd@mail.orb.ru',
      },
    ],
    or: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Артемов Андрей Владимирович',
        position: 'Заместитель руководителя Департамента – начальник управления информационных технологий Департамента информационных технологий Орловской области',
        phone: '+7 (4862) 59-88-51',
        email: 'avladar@adm.orel.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Абашин Александр Александрович',
        position: 'Начальник управления связи Департамента информационных технологий Орловской области',
        phone: '+7 (4862) 59-88-52',
        email: 'aaa@adm.orel.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Арабаджи Александр Александрович',
        position: 'Исполняющий обязанности начальника отдела информационной безопасности Департамента информационных технологий Орловской области',
        phone: '+7 (4862) 59-78-39',
        email: 'hpv@adm.orel.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Побережный Петр Анатольевич',
        position: 'Начальник отдела организации предоставления услуг в электронном виде управления информационных технологий Департамента информационных технологий Орловской области',
        phone: '+7 (4862) 59-88-54',
        email: 'ppa@adm.orel.ru',
      },
    ],
    pz: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Костин Алексей Владимирович',
        position: 'Начальник  Управления',
        phone: '+7 (8412) 66-00-45',
        email: 'kostin@obl.penza.net',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Чикин Руслан Вячеславович',
        position: 'Заместитель начальника Управления',
        phone: '+7 (8412) 66-00-45',
        email: 'chikin@obl.penza.net',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Майорова Жанна Сергеевна',
        position: 'Заместитель  начальника  Управления, начальник отдела внедрения',
        phone: '+7 (8412) 66-00-45',
        email: 'majorova@obl.penza.net',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Никишина Елена Викторовна',
        position: 'Консультант отдела внедрения',
        phone: '+7 (8412) 66-02-52',
        email: 'nikishina@obl.penza.net',
      },
    ],
    pe: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Маслов Александр Николаевич',
        position: 'Первый заместитель министра',
        phone: '+7 (342) 253-71-07',
        email: 'anmaslov@mirs.permkrai.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Еренков Александр Павлович',
        position: 'Заместитель начальника управления развития инфраструктуры',
        phone: '+7 (342) 253-69-30<br>(доб. 3)',
        email: 'aperenkov@mirs.permkrai.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Суханова Полина Андреевна',
        position: 'Советник заместителя Председателя Правительства Пермского края, руководитель проекта «Пермский сетевой ИТ-университет»',
        phone: '',
        email: 'pasukhanova@it.permkrai.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Набатова Екатерина Владимировна',
        position: 'Заместитель руководителя, начальник информационно–аналитического управления',
        phone: '',
        email: 'evnabatova@it.permkrai.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Косвинцев Николай Николаевич',
        position: 'Руководитель направления «Экосистема НТИ в Пермском крае»',
        phone: '',
        email: 'nkosvintcev@investinperm.ru',
      },
    ],
    pr: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Максимчук Сергей Васильевич',
        position: 'Врио вице-губернатора Приморского края – директор департамента информатизации и телекоммуникаций Приморского края',
        phone: '',
        email: 'maksimchuk_sv@primorsky.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Потапова Татьяна Леонидовна',
        position: 'Заместитель директора департамента',
        phone: '',
        email: 'Potapova_TL@primorsky.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Сясин Дмитрий Юрьевич',
        position: 'И.о. заместителя директора департамента',
        phone: '',
        email: 'Syasin_DY@primorsky.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Головачев Евгений Владимирович',
        position: 'Начальник отдела информационных систем',
        phone: '',
        email: 'Golovachev_EV@primorsky.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Якимовская Наталья Юрьевна',
        position: 'Начальник отдела электронного взаимодействия',
        phone: '',
        email: 'Yakimovskaya_NY@primorsky.ru',
      },
    ],
    ps: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Матвеев Денис Сергеевич',
        position: 'Начальник Управления цифрового развития и связи Администрации Псковской области',
        phone: '+7 (8112) 29-96-01',
        email: 'ds.matveev@obladmin.pskov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Рахманов Виталий Викторович',
        position: 'Первый заместитель начальника Управления цифрового развития и связи Администрации Псковской области',
        phone: '+7 (8112) 29-92-99<br>(доб. 102)',
        email: 'vv.rakhmanov@pskov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Смирнов Эдуард Сергеевич',
        position: 'Заместитель начальника отдела цифровых технологий Управления цифрового развития и связи Администрации Псковской области',
        phone: '+7 (8112) 29-92-99<br>(доб. 183)',
        email: 'es.smirnov@obladmin.pskov.ru',
      },
    ],
    ad: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Шу Заурбек Юсуфович',
        position: 'Министр',
        phone: '+7 (8772) 52-19-91',
        email: 'sovetnik@adygheya.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Семенцов Михаил Викторович',
        position: 'Первый заместитель Министра',
        phone: '+7 (8772) 57-08-25',
        email: 'm.sementsov@mincifra01.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Кахужев Тимур Довлетбиевич',
        position: 'Заместитель Министра',
        phone: '+7 (8772) 57-08-25',
        email: 't.kahuzhev@mincifra01.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Хатукай Аслан Адамович',
        position: 'Консультант',
        phone: '+7 (8772) 57-08-25',
        email: 'a.khatukay@mincifra01.ru',
      },
    ],
    lt: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Ротарь Федор Николаевич',
        position: 'Министр экономического развития и имущественных отношений Республики Алтай',
        phone: '+7 (38822) 2-65-95',
        email: 'mineco04@mail.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Белекова  Алтынсай Сергеевна',
        position: 'Заместитель министра экономического развития и имущественных отношений Республики Алтай',
        phone: '+7 (38822) 2-31-43',
        email: 'altynsay777@mail.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Дорохова Юлия Сергеевна',
        position: 'Начальник отдела по развитию информационных технологий министерства экономического развития и имущественных отношений Республики Алтай',
        phone: '+7 (38822) 2-26-08',
        email: 'info@mineco.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Зезиков Евгений Владимирович',
        position: 'Заместитель директора бюджетного учреждения Республики Алтай по эксплуатации радиорелейной линии связи «Эл Телком»',
        phone: '+7 (38822) 2-94-05<br>(доб. 133)',
        email: 'zezikov@eltelkom.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Долгов Петр Михайлович',
        position: 'Начальник отдела защиты информации Единого аппарата Главы Республики Алтай и Правительства Республики Алтай',
        phone: '+7 (38822) 2-41-17',
        email: 'dolgov@apra.gorny.ru',
      },
    ],
    bs: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Разумикин Геннадий Валентинович',
        position: 'И.о. председателя',
        phone: '+7 (347) 218-07-99',
        email: 'razumikin.gv@bashkortostan.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Слепов Денис Сергеевич',
        position: 'Первый заместитель председателя',
        phone: '+7 (347) 218-12-40',
        email: 'slepov.d@bashkortostan.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Таипов Расул Рафанирович',
        position: 'Заместитель председателя',
        phone: '+7 (347) 218-15-75',
        email: 'taipov.rr@bashkortostan.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Хаматвалиев Рустем Флюрович',
        position: 'Заместитель председателя',
        phone: '+7 (347) 218-08-06',
        email: 'Khamatvaliev.RF@Bashkortostan.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Шарафутдинов Динар Данилович',
        position: 'Заместитель председателя',
        phone: '+7 (347) 218-13-00',
        email: 'Sdd@bashkortostan.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Степанов Сергей Александрович',
        position: 'Начальник отдела информатизации органов власти – секретарь проектного комитета',
        phone: '+7 (347) 218-07-96',
        email: 'stepanov.sa@bashkortostan.ru',
      },
    ],
    br: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Комарь Павел Михайлович',
        position: 'Заместитель Председателя Комитета информационных технологий и документальной связи – Начальник отдела развития цифровой инфраструктуры',
        phone: '+7 (3012) 21-13-84<br>(доб. 301)',
        email: 'wolf@govrb.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Халбаев Максим Валерьевич',
        position: 'Начальник отдела развития технологий электронного государства',
        phone: '+7 (3012) 22-10-26<br>(доб. 201)',
        email: 'Khalbaev.m@govrb.ru',
      },
    ],
    da: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Снегирев  Сергей Владимирович',
        position: 'Министр информатизации, связи и массовых коммуникаций Республики Дагестан',
        phone: '+7 (8722) 51-03-60',
        email: 's.snegirev@minsvyazrd.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Магомедов Бадруттин Алиевич',
        position: 'И.о. первого заместителя министра информатизации, связи и массовых коммуникаций Республики Дагестан',
        phone: '+7 (8722) 51-03-67',
        email: 'badruttin@minsvyazrd.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Омарова Марина Александровна',
        position: 'Начальник управления по развитию электронного правительства и координации информатизации',
        phone: '+7 (8722) 51-03-58',
        email: 'm.omarova@minsvyazrd.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Абдулаев Шамиль Магомедович',
        position: 'Заместитель начальника управления по информационной безопасности и связи – начальник отдела развития инфраструктуры электронного правительства и связи',
        phone: '+7 (8722) 51-03-63',
        email: 'sh.abdulaev@minsvyazrd.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Меджидова Хава Сайдалиевна',
        position: 'Главный специалист-эксперт отдела развития сектора ИКТ услуг',
        phone: '+7 (8722) 51-03-64',
        email: 'kh.medzhidova@minsvyazrd.ru',
      },
    ],
    in: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Гелисханов Али Магометович',
        position: 'Заместитель Председателя Комитета транспорта, энергетики, связи и информатизации Республики Ингушетия',
        phone: '+7 (8734) 22-48-64',
        email: 'Gelishanov.A.M@ ingushetia.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Угурчиев Ислам Тагирович',
        position: 'Начальник отдела информационной инфраструктуры и информационной безопасности',
        phone: '+7 (8734) 22-48-50',
        email: 'Ugurchiev.IT@ ingushetia.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Хашагульгов Магомед Илесович',
        position: 'Главный специалист отдела информационной инфраструктуры и информационной безопасности',
        phone: '+7 (8734) 22-48-50',
        email: 'magaing006@mail.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Евкуров Хамзат Саварбекович',
        position: 'Главный специалист отдела цифровизации',
        phone: '+7 (8734) 22-48-50',
        email: 'Evkurov.HC@ ingushetia.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Кациев Ислам Русланович',
        position: 'Специалист 1-го разряда отдела цифровизации',
        phone: '+7 (8734) 22-48-50',
        email: 'it@komitetri.ru',
      },
    ],
    kk: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Этеев Алексей Петрович',
        position: 'Министр цифрового развития Республики Калмыкия',
        phone: '+7 (84722) 3-35-86',
        email: 'a.eteev@rk08.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Манджиева Байир Олеговна',
        position: 'Заместитель Министра цифрового развития Республики Калмыкия',
        phone: '+7 (84722) 3-35-86',
        email: 'b.mandzhieva@rk08.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Кичиков Александр Александрович',
        position: 'Начальника отдела информационных технологий Министерства цифрового развития Республики Калмыкия',
        phone: '+7 (84722) 3-35-87',
        email: 'a.kichikov@rk08.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Мирюшкина Марина Владимировна',
        position: 'Начальник отдела проектов цифровой трансформации Министерства цифрового развития Республики Калмыкия',
        phone: '+7 (84722) 3-35-87',
        email: 'm.miryushkina@rk08.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Бадма-Халгаева Гиляна Борисовна',
        position: 'Заместитель начальника отдела проектов цифровой трансформации Министерства цифрового развития Республики Калмыкия',
        phone: '+7 (84722) 3-35-87',
        email: 'g.badma.halgaeva@rk08.ru',
      },
    ],
    kl: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Никольская Наталья Васильевна',
        position: 'Заместитель Руководителя Администрации Главы Республики Карелия – начальник управления информатизации и защиты информации',
        phone: '+7 (8142) 79-93-47',
        email: 'nikolskaya@gov.karelia.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Малинов Дмитрий Станиславович',
        position: 'Заместитель начальника управления информатизации и защиты информации Администрации Главы Республики Карелия',
        phone: '+7 (8142) 76-99-89',
        email: 'malinov@gov.karelia.ru',
      },
    ],
    ko: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Майнина Кристина Андреевна',
        position: 'Начальник Управления цифрового развития, связи, массовых коммуникаций и рекламы',
        phone: '+7 (8212) 28-53-22',
        email: 'k.a.maynina@adm.rkomi.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Жиляев Дмитрий Витальевич',
        position: 'Начальник отдела развития цифровой экономики',
        phone: '+7 (8212) 28-55-61',
        email: 'd.v.zhilyaev@adm.rkomi.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Белых Олег Валерьевич',
        position: 'Начальник отдела информатизации, связи и рекламы',
        phone: '+7 (8212) 28-53-96',
        email: 'o.v.belyh@adm.rkomi.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Влох Артем Валерьевич',
        position: 'Заместитель начальника отдела информатизации, связи и рекламы',
        phone: '+7 (8212) 28-53-98',
        email: 'a.v.vloh@adm.rkomi.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Киселёва Екатерина Николаевна',
        position: 'Консультант-эксперт Сектора связи и организации эксплуатации отдела информатизации, связи и рекламы',
        phone: '+7 (8212) 28-54-23',
        email: 'e.n.kiseleva@adm.rkomi.ru',
      },
    ],
    cr: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Балацкий Максим Владимирович',
        position: 'Первый заместитель министра внутренней политики, информации и связи Республики Крым',
        phone: '+7 (3652) 60-59-35',
        email: 'delo@minfo.rk.gov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Семенченко Александр Николаевич',
        position: 'Начальник управления информатизации и развития информационных систем',
        phone: '+7 (3652) 60-59-42',
        email: 'a.semenchenko@minfo.rk.gov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Шмелёв Николай Ильич',
        position: 'Заместитель начальника управления по телекоммуникациям и связи, заведующий отделом инновационного развития',
        phone: '+7 (3652) 60-59-34',
        email: 'n.shmelev@minfo.rk.gov.ru',
      },
    ],
    ml: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Кадыков Анатолий Витальевич',
        position: 'Заметитель руководителя Департамента',
        phone: '+7 (8363) 63-00-50',
        email: 'kadykov@gov.mari.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Куклина Галина Ивановна',
        position: 'Начальник отдела информационных технологий Департамента',
        phone: '+7 (8362) 64-18-50',
        email: 'disit@gov.mari.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Шершнев Юрий Викторович',
        position: 'Начальник отдела финансово-правового обеспечения и информационной безопасности Департамента',
        phone: '+7 (8362) 64-11-87',
        email: 'shershnev@gov.mari.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Илларионова Наталья Николаевна',
        position: 'Консультант информационно-аналитического отдела Департамента',
        phone: '+7 (8362) 64-18-40',
        email: 'nata@gov.mari.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Смирнов Евгений Владимирович',
        position: 'Начальник информационно-аналитического отдела Департамента',
        phone: '+7 (8362) 64-17-67',
        email: 'smirnov@gov.mari.ru',
      },
    ],
    mr: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Вольфсон Игорь Анатольевич',
        position: 'Министр информатизации и связи Республики Мордовия',
        phone: '+7 (8342) 39-14-01',
        email: 'i.volfson@e-mordovia.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Соколов Олег Александрович',
        position: 'Первый заместитель Министра – начальник управления цифрового развития',
        phone: '+7 (8342) 39-14-14',
        email: 'osokolov@e-mordovia.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Конев Сергей Александрович',
        position: 'Начальник отдела программ и проектов информационного общества и электронного правительства',
        phone: '+7 (8342) 39-14-09',
        email: 'konevsa@e-mordovia.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Санина Наталья Владимировна',
        position: 'Заместитель начальника отдела программ и проектов информационного общества и электронного правительства',
        phone: '+7 (8342) 39-14-26',
        email: 'sanina@e-mordovia.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Сюваева Анастасия Евгеньевна',
        position: 'Консультант отдела информационных технологий и информационных ресурсов',
        phone: '+7 (8342) 39-14-27',
        email: 'syuvaevaae@e-mordovia.ru',
      },
    ],
    sa: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Гришаев Николай Викторович',
        position: 'Первый заместитель министра',
        phone: '+7 (4112) 39-82-01',
        email: 'grishaev.nikolay@sakha.gov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Николаев Петр Васильевич',
        position: 'Руководитель отдела цифрового развития',
        phone: '+7 (4112) 39-82-07',
        email: 'Nikolaev.Petr@sakha.gov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Исаева Анна Сергеевна',
        position: 'Руководитель отдела государственной политики в области связи',
        phone: '+7 (4112) 50-60-19',
        email: 'isaevaas@sakha.gov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Лыткин Сергей Николаевич',
        position: 'Руководитель отдела информационной безопасности',
        phone: '+7 (4112) 50-60-22',
        email: 'lytkin.sergey@sakha.gov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Слепцов Иннокентий Степанович',
        position: 'Руководитель отдела инновационного развития',
        phone: '+7 (4112) 50-62-48',
        email: 'sleptsov.innokentiy@sakha.gov.ru',
      },
    ],
    so: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Салбиев Алан Тасолтанович',
        position: 'Руководитель управления',
        phone: '+7 (8672) 40-50-85',
        email: 'a.salbiev@it.alania.gov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Кулаева Марина Владимировна',
        position: 'Заместитель руководителя управления',
        phone: '+7 (8672) 40-50-85',
        email: 'kulayeva@yandex.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Дзоблаев Алан Валерьевич',
        position: 'Начальник административно-правового отдела',
        phone: '+7 (8672) 40-50-89<br>(доб. 506)',
        email: 'a.dzoblaev@it.alania.gov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Марзаев Георгий Борисович',
        position: 'Начальник отдела информационных технологий',
        phone: '+7 (8672) 40-50-89<br>(доб. 514)',
        email: 'g.marzaev@it.alania.gov.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Кулиев Алан Алексеевич',
        position: 'Начальник отдела защиты информации',
        phone: '+7 (8672) 40-50-89<br>(доб. 502)',
        email: 'a.kuliev@it.alania.gov.ru',
      },
    ],
    ta: [
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Мугинов Азат Рустамович',
        position: 'Заместитель министра',
        phone: '+7 (843) 231-77-47',
        email: 'Azat.Muginov@tatar.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Исмагилов Булат Ибрагимович',
        position: 'Заместитель министра',
        phone: '+7 (843) 231-77-02',
        email: 'Bulat.Ismagilov@tatar.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Афанасьева Светлана Николаевна',
        position: 'Начальник отдела кадров',
        phone: '+7 (843) 231-77-90',
        email: 'Svetlana.Afanaseva@tatar.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Ерастов Артем Алексеевич',
        position: 'Ведущий консультант сектора информационной безопасности',
        phone: '+7 (843) 231-77-56',
        email: 'Artem.Erastov@tatar.ru',
      },
      {
        photo: window.cekiContacts.linkForWebtutor + 'img/no_foto.svg',
        name: 'Фатыхова Юлия Рамилевна',
        position: 'Менеджер проектов отдела планирования и развития',
        phone: '+7 (843) 264-73-00<br>(доб. 2058)',
        email: 'Y.Bakirova@tatar.ru',
      },
    ],
  };
}(window.regionContacts));
